version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: architecture-boilerplate-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: architecture_boilerplate
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
